# Generated by Django 4.2.6 on 2023-10-18 16:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Anime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="Название")),
                (
                    "japan_title",
                    models.CharField(max_length=256, verbose_name="Японское назввание"),
                ),
                ("slug", models.SlugField(max_length=256, verbose_name="Слаг")),
                (
                    "description",
                    models.CharField(max_length=4096, verbose_name="Описание"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("tv", "Тв-сериал"),
                            ("movie", "Аниме-фильм"),
                            ("ova", "Ova"),
                        ],
                        max_length=64,
                        verbose_name="Тип показа",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ongoing", "Онгоинг"),
                            ("completed", "Завершённое"),
                            ("upcoming", "Ожидается"),
                        ],
                        max_length=64,
                        verbose_name="Статус",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "released_episodes",
                    models.IntegerField(verbose_name="Вышедшие эпизоды"),
                ),
                (
                    "planned_episodes",
                    models.IntegerField(verbose_name="Запланируемые эпизоды"),
                ),
                (
                    "views",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Просмотры"
                    ),
                ),
                (
                    "poster",
                    models.ImageField(upload_to="posters/", verbose_name="Постер"),
                ),
                (
                    "poster_for_main_page",
                    models.ImageField(
                        upload_to="posters_main/",
                        verbose_name="Постер на главной странице",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Аниме",
                "verbose_name_plural": "Аниме",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Название")),
                ("slug", models.SlugField(max_length=128, verbose_name="Слаг")),
                (
                    "description",
                    models.CharField(max_length=4096, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="Название")),
                ("slug", models.SlugField(max_length=128, verbose_name="Слаг")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=4096, verbose_name="Описание серии"
                    ),
                ),
                (
                    "video",
                    models.FileField(upload_to="episodes/", verbose_name="Эпизод"),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anime.anime",
                        verbose_name="Аниме",
                    ),
                ),
            ],
            options={
                "verbose_name": "Эпизод",
                "verbose_name_plural": "Эпизоды",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Название")),
                ("slug", models.SlugField(max_length=128, verbose_name="Слаг")),
                (
                    "description",
                    models.CharField(max_length=4096, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
            },
        ),
        migrations.CreateModel(
            name="Studio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Название")),
                ("slug", models.SlugField(max_length=128, verbose_name="Слаг")),
                (
                    "description",
                    models.CharField(max_length=4096, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Студия",
                "verbose_name_plural": "Студии",
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anime.anime",
                        verbose_name="Аниме",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка",
                "verbose_name_plural": "Оценки",
            },
        ),
        migrations.CreateModel(
            name="FollowingAnime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anime.anime",
                        verbose_name="Аниме",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отслеживаемое аниме",
                "verbose_name_plural": "Отслеживаемые аниме",
            },
        ),
        migrations.CreateModel(
            name="EpisodeReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=512, verbose_name="Текст")),
                ("is_spoiler", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anime.episode",
                        verbose_name="Эпизод",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий к эпизоду",
                "verbose_name_plural": "Комментарии к эпизодам",
            },
        ),
        migrations.CreateModel(
            name="AnimeReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=512, verbose_name="Текст")),
                ("is_spoiler", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anime.anime",
                        verbose_name="Аниме",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий к аниме",
                "verbose_name_plural": "Комментарии к аниме",
            },
        ),
        migrations.AddField(
            model_name="anime",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="animes",
                to="anime.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="anime",
            name="genres",
            field=models.ManyToManyField(to="anime.genre", verbose_name="Жанры"),
        ),
        migrations.AddField(
            model_name="anime",
            name="studio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="animes",
                to="anime.studio",
                verbose_name="Студия",
            ),
        ),
    ]
