# Generated by Django 4.2.6 on 2023-11-17 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0002_anime_is_draft_animereview_parent_episodeshots_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodereview",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="anime.episodereview",
                verbose_name="Родитель",
            ),
        ),
        migrations.AlterField(
            model_name="anime",
            name="status",
            field=models.CharField(
                choices=[
                    ("Онгоинг", "Ongoing"),
                    ("Завершён", "Completed"),
                    ("Ожидается", "Planned"),
                ],
                max_length=64,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="anime",
            name="type",
            field=models.CharField(
                choices=[
                    ("Тв-сериал", "Tv-serial"),
                    ("Фильм", "Movie"),
                    ("Oва", "Ova"),
                ],
                max_length=64,
                verbose_name="Тип показа",
            ),
        ),
    ]
