# Generated by Django 4.2.6 on 2023-11-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0003_episodereview_parent_alter_anime_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studio",
            name="image",
            field=models.ImageField(
                null=True, upload_to="posters/", verbose_name="Постер"
            ),
        ),
    ]
