# Generated by Django 4.2.6 on 2023-11-28 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0004_studio_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="rating",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Рейтинг",
            ),
        ),
    ]
