# Generated by Django 4.2.6 on 2023-12-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0005_alter_vote_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="duration",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Длительность"
            ),
        ),
    ]
