# Generated by Django 4.2.6 on 2023-12-06 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0007_anime_quality_alter_anime_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="quality",
            field=models.CharField(
                choices=[
                    ("Full HD", "Full High Definition 1080p"),
                    ("HD", "High Definition 720p"),
                    ("HQ", "High Quality 480p"),
                    ("SD", "Standard definition 360p"),
                    ("Пока не объявлено", "Пока неизвестно"),
                ],
                default="Пока не объявлено",
                max_length=128,
                verbose_name="Качество",
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="anime",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="episodes",
                to="anime.anime",
                verbose_name="Аниме",
            ),
        ),
    ]
