# Generated by Django 4.2.6 on 2023-12-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0010_alter_account_options_alter_account_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=128, unique=True, verbose_name="Слаг"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="account",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="Аватарка"
            ),
        ),
    ]
