# Generated by Django 4.2.6 on 2023-12-24 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("anime", "0011_account_slug_alter_account_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followinganime",
            name="anime",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following_anime",
                to="anime.anime",
                verbose_name="Аниме",
            ),
        ),
        migrations.AlterField(
            model_name="followinganime",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following_anime",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
